version: '3.8'

services:
  api:
    build: .
    container_name: fastapi-poc
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=${APP_NAME:-FastAPI POC}
      - VERSION=${VERSION:-0.1.0}
      - DEBUG=${DEBUG:-true}
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api